### ISSUE TITLE
Make dropdowns for Specification and Configuration searchable

### ISSUE THREAD

**Issue by leostrakosch** [SupunArunoda/CPACEP#5]
There can be a lot of configurations, so searching by letters would be helpful.
E.g., when typing `v`, the dropdown should jump to the first entry that starts with a v.
To make behavior consistent, this should also be enabled for the specification dropdown.

**Comment by leostrakosch** [comment]
Reopen due to premature merge of PR.
Please try to keep discipline.

**Comment by leostrakosch** [comment]
Works nice! Do you think it would be easy to also allow entering multiple letters, e.g., `pr` for `predicateAnalysis`?

**Comment by SupunArunoda** [comment]
How about adding **_pA_** for predicateAnalysis like we do shortcuts in developer tools?

**Comment by leostrakosch** [comment]
Unless we can create a generic rule for this, I think it would be easier to enter the 'n' first letters.
So you do think it would be easy to allow this?

**Comment by SupunArunoda** [comment]
Hi Thomas,
I checked the current situation. It works like you wish. Since we ordered alphabetically specifications and configurations the first word will be taken. Check the attach screen-shot.  Let me know if there is an further improvements.

![screenshot from 2018-06-16 09-39-39](https://user-images.githubusercontent.com/12041588/41495652-acee52fe-7149-11e8-8a91-d5ac155c7bc0.png)

**Comment by leostrakosch** [comment]
Ok, this is different from what I meant, but also really nice!

**Comment by leostrakosch** [comment]
Ok, this is different from what I meant, but also really nice!
